README.md
bingo/.gitignore

Added Basic README
Fixes # Initialize Project Add README

added basic README

---

bingo/src/App.js
bingo/src/components/billing.js
bingo/src/components/index.js
bingo/src/components/setting.js

Adding billing and settings routes to the front end.
Fixes # Billing and Settings Routes

billing & settings page routes

---

backend/package.json
backend/server.js
backend/yarn.lock

Fixes # Client app in development mode can not make requests to backend

added cors for client app

---

backend/server.js

Reset Password

---

client/src/components/card.js
client/src/components/cards.js
client/src/components/index.js
client/src/index.js

Added a protected route for Card (individual card for Create/Edit).
Fixes # Card Route

added route to single card create & edit

---

backend/models/user.js
backend/server.js

Fixes # Responses now return a 403 or 422 status code with error messages. Fixes a bug checking the authentication of a user.

password and status codes

---

client/src/index.js

adding redux dev tools plugin

---

client/src/actions/index.js
client/src/components/card.js
client/src/components/cardCreate.js
client/src/components/cards.js
client/src/components/index.js
client/src/index.js
client/src/reducers/cardReducer.js
client/src/reducers/cardsReducer.js
client/src/reducers/index.js

Cards Route pulls from database and maps over data to display (right now no cards data so no display)
Fixes # Cards Route pulls from database

Cards route

---

backend/package.json
backend/server.js
backend/yarn.lock
client/src/actions/index.js
client/src/components/bingo.css
client/src/components/bingo.js
client/src/components/cardCreate.js
client/src/components/protectedComponent.css

Adds card generation to backend and frontend

---

client/src/actions/index.js
client/src/components/HOC/RequireAuth.js
client/src/components/header.js

Fixes # Auth Flow fixes, keeps auth on refresh, etc. 

Auth flow fixes

---

backend/server.js

fix build output path - fixes heroku

---

client/src/actions/index.js

Fixes # changes urls to heroku url for api calls. 

change client url when on heroku

---

client/src/actions/index.js

Fixes # (issue) Check if in production

check if in production

---

client/src/actions/index.js

Fixes # (issue) HTTPS-only requests on heroku page

force https

---

client/src/components/billing.js
client/src/components/breadcrumbs.js
client/src/components/card.js
client/src/components/cardCreate.js
client/src/components/cards.js
client/src/components/header.js
client/src/components/protectedComponent.css
client/src/components/settings.js
client/src/components/sidenav.js

Added breadcrumb navigation
Fixes # Navigation >> Breadcrumbs

breadcrumbs

---

client/src/actions/index.js
client/src/components/cardEdit.js
client/src/components/index.js
client/src/index.js
client/src/reducers/cardsReducer.js

Added client side route to edit card by id
Fixes # Edit Route

added edit by id route

---

client/public/index.html
client/src/components/landing.css
client/src/components/landing.js

Udated landing page
Fixes # Landing Page

updated landing page

---

client/src/components/landing.css

Fixed content width to allow for larger screens
Fixes # content did not fill width of screen on larger screens

fixed content width for larger screens

---

package.json
yarn.lock

Fixes #  Fixes heroku deployment

fix heroku

---

client/public/pdf.html
client/public/pdf/BingoCard.js
client/public/pdf/buy/index2.js
client/public/pdf/buy/pdf.html
client/public/pdf/index.js
client/public/pdf/util.js
client/src/components/billing/form.js

Changes how data is transferred.
Update billing form to take this into account.

Sondro pdf 05

---

client/src/components/billing/form.js

Passing card object to server
Fixes # gets card object to server

pass card object to server

---

client/public/pdf/buy/index2.js
client/public/pdf/index.js

BingoCard iframe demo/bug fix

---

backend/controllers/Card.js
backend/server.js
client/src/actions/auth.js
client/src/actions/billing.js
client/src/actions/card.js
client/src/actions/index.js
client/src/components/bingo/pdf.js
client/src/components/cards/edit.js
client/src/components/user/settings.js

Update Herouku Production URL

---

client/src/components/landing.js

add some basic landing styles
